// AUTH ACTIONS // 
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const GET_QUIZ_FAIL = "GET_QUIZ_FAIL"

// PROFILE ACTIONS //
export const EDIT_PROFILE_SUCCESS = "EDIT_PROFILE_SUCCESS"
export const EDIT_PROFILE_FAIL = "EDIT_PROFILE_FAIL"
export const DELETE_PROFILE_SUCCESS = "DELETE_PROFILE_SUCCESS"
export const DELETE_PROFILE_FAIL = "DELETE_PROFILE_FAIL"

// PLATFORM ACTIONS //
export const GET_PLATFORM_REQ = "GET_PLATFORM_REQ"
export const CREATE_PLATFORM_REQ = "CREATE_PLATFORM_REQ"
export const DELETE_PLATFORM_REQ = "DELETE_PLATFORM_REQ"
export const JOIN_PLATFORM_REQ = "JOIN_PLATFORM_REQ"
export const LEAVE_PLATFORM_REQ = "LEAVE_PLATFORM_REQ"
export const REPORT_PLATFORM_REQ = "REPORT_PLATFORM_REQ"
export const GET_PLATFORM_SUCCESS = "GET_PLATFORM_SUCCESS"
export const GET_PLATFORM_FAIL = "GEt_PLATFORM_FAIL"
export const CREATE_PLATFORM_SUCCESS = "CREATE_PLATFORM_SUCCESS"
export const CREATE_PLATFORM_FAIL = "CREATE_PLATFORM_FAIL"
export const DELETE_PLATFORM_SUCCESS = "DELETE_PLATFORM_SUCCESS"
export const DELETE_PLATFORM_FAIL = "DELETE_PLATFORM_FAIL"
export const JOIN_PLATFORM_SUCCESS = "JOIN_PLATFORM_SUCCESS"
export const JOIN_PLATFORM_FAIL = "JOIN_PLATFORM_FAIL"
export const LEAVE_PLATFORM_SUCCESS = "LEAVE_PLATFORM_SUCCESS" 
export const LEAVE_PLATFORM_FAIL = "LEAVE_PLATFORM_FAIL"
export const REPORT_PLATFORM_SUCCESS = "REPORT_PLATFORM_SUCCESS" 
export const REPORT_PLATFORM_FAIL = "REPORT_PLATFORM_FAIL"

// QUIZ ACTIONS //
export const QUIZ_LOADING = "QUIZ_LOADING"
export const GET_QUIZ = "GET_QUIZ"