// AUTH ACTIONS // 
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"

// PROFILE ACTIONS //
export const EDIT_PROFILE_SUCCESS = "EDIT_PROFILE_SUCCESS"
export const EDIT_PROFILE_FAIL = "EDIT_PROFILE_FAIL"
export const DELETE_PROFILE_SUCCESS = "DELETE_PROFILE_SUCCESS"
export const DELETE_PROFILE_FAIL = "DELETE_PROFILE_FAIL"

// PLATFORM ACTIONS //
export const GET_PLATFORM_REQ = "GET_PLATFORM_REQ"
export const CREATE_PLATFORM_REQ = "CREATE_PLATFORM_REQ"
export const EDIT_PLATFORM_REQ = "EDIT_PLATFORM_REQ"
export const DELETE_PLATFORM_REQ = "DELETE_PLATFORM_REQ"
export const JOIN_PLATFORM_REQ = "JOIN_PLATFORM_REQ"
export const LEAVE_PLATFORM_REQ = "LEAVE_PLATFORM_REQ"
export const REPORT_PLATFORM_REQ = "REPORT_PLATFORM_REQ"
export const GET_PLATFORM_SUCCESS = "GET_PLATFORM_SUCCESS"
export const GET_PLATFORM_FAIL = "GEt_PLATFORM_FAIL"
export const CREATE_PLATFORM_SUCCESS = "CREATE_PLATFORM_SUCCESS"
export const CREATE_PLATFORM_FAIL = "CREATE_PLATFORM_FAIL"
export const EDIT_PLATFORM_SUCCESS = "EDIT_PLATFORM_SUCCESS"
export const EDIT_PLATFORM_FAIL = "EDIT_PLATFORM_FAIL"
export const DELETE_PLATFORM_SUCCESS = "DELETE_PLATFORM_SUCCESS"
export const DELETE_PLATFORM_FAIL = "DELETE_PLATFORM_FAIL"
export const JOIN_PLATFORM_SUCCESS = "JOIN_PLATFORM_SUCCESS"
export const JOIN_PLATFORM_FAIL = "JOIN_PLATFORM_FAIL"
export const LEAVE_PLATFORM_SUCCESS = "LEAVE_PLATFORM_SUCCESS" 
export const LEAVE_PLATFORM_FAIL = "LEAVE_PLATFORM_FAIL"
export const REPORT_PLATFORM_SUCCESS = "REPORT_PLATFORM_SUCCESS" 
export const REPORT_PLATFORM_FAIL = "REPORT_PLATFORM_FAIL"

// QUIZ ACTIONS //
export const QUIZ_LOADING = "QUIZ_LOADING"
export const GET_QUIZ = "GET_QUIZ"
export const GET_QUIZ_FAIL = "GET_QUIZ_FAIL"

export const CREATE_QUIZ_REQ = "CREATE_QUIZ_REQ"
export const CREATE_QUIZ_SUCCESS = "CREATE_QUIZ_SUCCESS"
export const CREATE_QUIZ_FAIL = "CREATE_QUIZ_FAIL"
export const EDIT_QUIZ = "EDIT_QUIZ"
export const EDIT_QUIZ_FAIL = "EDIT_QUIZ_FAIL"
export const DELETE_QUIZ = "DELETE_QUIZ"
export const DELETE_QUIZ_FAIL = "DELETE_QUIZ_FAIL"

// QUESTION ACTIONS //
export const ADD_QUIZ_QUESTION = "ADD_QUIZ_QUESTION"
export const ADD_QUIZ_QUESTION_FAIL = "ADD_QUIZ_QUESTION_FAIL"
export const EDIT_QUIZ_QUESTION = "EDIT_QUIZ_QUESTION"
export const EDIT_QUIZ_QUESTION_FAIL = "EDIT_QUIZ_QUESTION_FAIL"
export const DELETE_QUIZ_QUESTION = "DELETE_QUIZ_QUESTION"
export const DELETE_QUIZ_QUESTION_FAIL = "DELETE_QUIZ_QUESTION_FAIL"

// AWARD ACTIONS // 
export const CREATE_AWARD_REQ = "CREATE_AWARD_REQ"
export const CREATE_AWARD_SUCCESS = "CREATE_AWARD_SUCCESS"
export const CREATE_AWARD_FAIL = "CREATE_AWARD_FAIL"
export const EDIT_AWARD_REQ = "EDIT_AWARD_REQ"
export const EDIT_AWARD_SUCCESS = "EDIT_AWARD_SUCCESS"
export const EDIT_AWARD_FAIL = "EDIT_AWARD_FAIL"
export const DELETE_AWARD_REQ = "DELETE_AWARD_REQ"
export const DELETE_AWARD_SUCCESS = "DELETE_AWARD_SUCCESS"
export const DELETE_AWARD_FAIL = "DELETE_AWARD_FAIL"

// SUBMISSION ACTIONS //
export const CREATE_SUBMISSION = "CREATE_SUBMISSION"
export const CREATE_SUBMISSION_FAIL = "CREATE_SUBMISSION_FAIL"